### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ducky443747** [carbonnetwork-dev/Carbon#1]
Every time I run this, it says "Connection was reset" when I try and open a new tab.

**Comment by ImPosh** [comment]
Just restart your computer and re run the file. I can not do anything to fix that

**Comment by ImPosh** [comment]
Im not exactly sure try deleting and re downloading the file. I will try to fix that issue

**Comment by insert-text-here** [comment]
if it does its most likely a ip block try using a vpn or smth
i heard theres a way to disable wifi blocks by settings to metered network as well, but the admins probably already require you to use direct

**Comment by insert-text-here** [comment]
well, go to chrome://network
and then, scroll down and find "import ONC file"
then, import this file I'm going to put here.
in your stuff, it should show "VPN". that might be a bit risky if the school finds out, but it might work.
also, what type of computer are you using? that might also be a factor, because I wrote the original comment assuming it was chromebook, but might not be.
(the file is not an mp4, convert to .onc by renaming the file, its just that github is a poopoohead and doesnt let you import onc files)
https://user-images.githubusercontent.com/125519936/232605437-62a386fe-6ca9-4fe7-8b94-f7ca8c91f4e4.mp4

**Comment by insert-text-here** [comment]
oh, I just noticed the file doesnt work. here is a google drive link instead.
https://drive.google.com/file/d/1-bOmCNMV7wjS1z5RBZdKUDx5gXdMiXBR/view?usp=sharing

**Comment by Ducky443747** [comment]
i use windows, is there any way to do this with windows? thank you if you can help

**Comment by Ducky443747** [comment]
i reopened this because somehow (unsure though) it started working just about a week ago. And now, I'm not sure what happened but just last friday it was working and then when I tried to run it now it brought the same error up. My only suggestion would be redoing whatever you did in 1.01 and 1.02. Thanks for making this program btw, while it was unblocked, it was super fun to play any game I wanted.
